name: "Deploy App"

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          #Set Java Version
          java-version: '20'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/CupWithMe-win.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          #Set dockerhub username
          username: sia1981
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          #Set dockerhub project (replace "bartfastiel/java-capstone-project.de-example-app")
          tags: sia1981/cupwithme-win:latest
          context: .

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Restart docker container
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-126-121-48.eu-central-1.compute.amazonaws.com
          #Set App Name (replace "example" with "alpha"-"tango")
          username: cupwithme-win
          ssh-key: ${{ secrets.EC2_PRIVATE_KEY  }}
          #Set App Name (replace "example" with "alpha"-"tango")
          #Set dockerhub project (replace "bartfastiel/java-capstone-project.de-example-app")
          #Set IP (replace "10.0.1.99" with "10.0.1.1"-"10.0.1.20")
          script: |
            sudo docker stop  cupwithme-win
            sudo docker rm cupwithme-win
            sudo docker run --pull=always --name cupwithme-win --ip 172-31-23-12 --restart always --detach --env MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} sia1981/cupwithme-win:latest
            sleep 15s
            sudo docker logs cupwithme-win

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set App Name (replace "example" with "alpha"-"tango")
          url:  http://ec2-3-126-121-48.eu-central-1.compute.amazonaws.com
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
