name: "Get Logs"

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Get logs from docker
        uses: appleboy/ssh-action@master
        with:
          host: 3.126.121.48
          #Set App Name (replace "example" with "alpha"-"tango")
          username: ec2-user
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          #Set App Name (replace "example" with "alpha"-"tango")
          script: |
            sudo docker logs cupwithme-win
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set App Name (replace "example" with "alpha"-"tango")
          url: http://3.126.121.48
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
